# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 
        pip install gitpython
        pip install jira
        pip install termcolor 
        pip install openpyxl  

    
    - name: Checkout bugminer
      uses: actions/checkout@v2
      with:
        repository: rotba/BugMiner
        path: .
        fetch-depth: 0
    
    - name: Checkout javadiff
      uses: actions/checkout@v2
      with:
        repository: amir9979/javadiff
        path: ./javadiff
        fetch-depth: 0
    
    - name: execute miner
      run: python Main.py https://github.com/apache/tika http:\issues.apache.org\jira\projects\TIKA 65ae67eb163918d449242b47c2bfbb3cd99d7ecd


